### ISSUE TITLE
Add more Classmap Sequences

### ISSUE THREAD

**Issue by srfoster** [thoughtstem/mc-classmaps#14]
I've started to build the UI for browsing/navigating Classmaps via Sequences (https://github.com/thoughtstem/mc-classmaps/issues/13).  

To really test the UI, though, we'll need more Sequences.  Can you add in the ones that have been designed/discussed so far?

**Comment by sglucchini** [comment]
Added the three levels of academic map sequences designed for TPES in school:
Computational thinking (for kinder)
"                        "              for lower elementary
"                        "              for upper elementary
