### ISSUE TITLE
classmaps rendering time bug

### ISSUE THREAD

**Issue by sglucchini** [thoughtstem/mc-classmaps#2]
Should render times according to percentage of total time. example for clarification:

A class map with 3 10 min segments should display as:
3 20 min segments for a 1 hour session
3 30 min segments for a 1.5 hour session
3 10 min segments for a 30 min session
etc

**Comment by srfoster** [comment]
I removed the time picking feature.  So this is no longer a bug.  If we choose to reimplement it, we can do so in a less buggy way.
