### ISSUE TITLE
gap in map if length of section is less than 5 min

### ISSUE THREAD

**Issue by sglucchini** [thoughtstem/mc-classmaps#4]
Sample below:

![Screen Shot 2019-12-04 at 4 35 36 PM](https://user-images.githubusercontent.com/23484593/70193508-440f5000-16b4-11ea-94fc-f9c2480ffa66.png)

**Comment by sglucchini** [comment]
clarification -- if section is less than 1/12th of total length ( ex: 5 min out of 60 min)

**Comment by srfoster** [comment]
Just fixed this.
